# Generated by Django 6.0.3 on 2026-03-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_freelancerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='experience',
        ),
    ]
