# Generated by Django 6.0.3 on 2026-03-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_freelancerprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
