# Generated by Django 6.0.3 on 2026-03-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_freelancerprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='username',
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='bio',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
