# Generated by Django 6.0.3 on 2026-03-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('design', 'Design'), ('mobile', 'Mobile Development'), ('writing', 'Content Writing'), ('data', 'Data Science')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
