# Generated by Django 6.0.3 on 2026-03-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.AddField(
            model_name='project',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('milestone', 'Milestone')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.CharField(choices=[('entry', 'Entry'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('design', 'Design'), ('mobile', 'Mobile Development'), ('writing', 'Content Writing'), ('data', 'Data Science'), ('ai', 'AI / ML')], max_length=20),
        ),
    ]
