# Generated by Django 6.0.3 on 2026-05-18 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bid', 'Yangi ariza'), ('bid_accepted', 'Ariza qabul qilindi'), ('bid_rejected', 'Ariza rad etildi'), ('contract', 'Shartnoma yaratildi'), ('contract_finished', 'Shartnoma tugatildi'), ('contract_cancelled', 'Shartnoma bekor qilindi'), ('review', 'Sharh qoldirildi'), ('message', 'Yangi xabar')], max_length=30)),
                ('text', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
