# Generated by Django 6.0.3 on 2026-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='finished_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
