# Generated by Django 6.0.3 on 2026-03-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0003_bid_finished_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='message',
            new_name='xabar',
        ),
    ]
