# Generated by Django 6.0.3 on 2026-05-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0004_rename_message_bid_xabar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='bids/'),
        ),
        migrations.AddField(
            model_name='bid',
            name='delivery_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
